default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST") { "127.0.0.1" } %>
  port: <%= ENV.fetch("DATABASE_PORT") { 3306 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { "root" } %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  ssl_mode: <%= ENV.fetch("DATABASE_SSL_MODE") { "disabled" }.to_sym %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") { "todo_app_development" } %>

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME_TEST") { "todo_app_test" } %>

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") { "todo_app_production" } %>
