name: CI/CD Pipeline Docker to Render

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Đăng nhập vào Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build và Push Docker Image
      uses: docker/build-push-action@v7
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/todo-app:latest

    - name: Kích hoạt Deploy trên Render
      run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
